# Generated by Django 3.2.12 on 2022-12-13 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('ig', models.CharField(blank=True, max_length=500, null=True)),
                ('sector', models.CharField(max_length=50)),
                ('provincia', models.CharField(max_length=20)),
                ('municipio', models.CharField(max_length=20)),
                ('referencia', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('telf', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='fotos')),
            ],
        ),
    ]
