# Generated by Django 3.2.12 on 2022-12-13 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20221213_0348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagen',
            name='estado',
        ),
    ]
