# Generated by Django 3.2.12 on 2022-12-13 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_imagen_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.estado'),
            preserve_default=False,
        ),
    ]
