# Generated by Django 3.2.12 on 2023-01-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_imagen_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto1', models.CharField(max_length=500)),
                ('texto2', models.CharField(max_length=300)),
                ('imagen', models.ImageField(upload_to='about')),
            ],
        ),
        migrations.RenameField(
            model_name='imagen',
            old_name='sector',
            new_name='categoria',
        ),
    ]
