# Generated by Django 3.2.12 on 2023-01-05 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_datos_para_about_miembros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='ig',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagen',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
