# Generated by Django 3.2.12 on 2023-01-15 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230105_2141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Datos_para_about',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='texto1',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='texto2',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub1en',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub1es',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub2en',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub2es',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub3en',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub3es',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub4en',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='sub4es',
            field=models.CharField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='texto1es',
            field=models.CharField(default=1, max_length=5000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='texto1esn',
            field=models.CharField(default=1, max_length=5000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='texto2en',
            field=models.CharField(default=1, max_length=5000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='texto2es',
            field=models.CharField(default=1, max_length=5000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='texto3en',
            field=models.CharField(default=1, max_length=5000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='texto3es',
            field=models.CharField(default=1, max_length=5000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='texto4en',
            field=models.CharField(default=1, max_length=5000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='texto4es',
            field=models.CharField(default=1, max_length=5000000),
            preserve_default=False,
        ),
    ]
