# Generated by Django 3.2.12 on 2023-01-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20230115_2110'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Historia', 'verbose_name_plural': 'Historia'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='imagen',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='sub1es',
            field=models.CharField(max_length=10000, verbose_name='Subtitulo 1 esp'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='sub2es',
            field=models.CharField(max_length=10000, verbose_name='Subtitulo 2 esp'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='sub3es',
            field=models.CharField(max_length=10000, verbose_name='Subtitulo 3 esp'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='sub4es',
            field=models.CharField(max_length=10000, verbose_name='Subtitulo 4 esp'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto1es',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto2es',
            field=models.CharField(max_length=5000000, verbose_name='Texto 2 esp'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto3es',
            field=models.CharField(max_length=5000000, verbose_name='Texto 3 esp'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto4es',
            field=models.CharField(max_length=5000000, verbose_name='Texto 4 esp'),
        ),
    ]
