# Generated by Django 3.2.12 on 2023-01-15 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20230115_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='sub1en',
            field=models.CharField(max_length=10000, verbose_name='Subtitulo 1 ing'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='sub2en',
            field=models.CharField(max_length=10000, verbose_name='Subtitulo 2 ing'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='sub3en',
            field=models.CharField(max_length=10000, verbose_name='Subtitulo 3 ing'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='sub4en',
            field=models.CharField(max_length=10000, verbose_name='Subtitulo 4 ing'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto1es',
            field=models.TextField(verbose_name='Texto 1 esp'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto1esn',
            field=models.TextField(verbose_name='Texto 1 ing'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto2en',
            field=models.TextField(verbose_name='Texto 2 ing'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto2es',
            field=models.TextField(verbose_name='Texto 2 esp'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto3en',
            field=models.TextField(verbose_name='Texto 3 ing'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto3es',
            field=models.TextField(verbose_name='Texto 3 esp'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto4en',
            field=models.TextField(verbose_name='Texto 4 ing'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texto4es',
            field=models.TextField(verbose_name='Texto 4 esp'),
        ),
    ]
