# Generated by Django 3.2.12 on 2023-01-16 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20230115_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='sub1en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='sub1es',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='sub2en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='sub2es',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='sub3en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='sub3es',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='sub4en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='sub4es',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='texto1es',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='texto1esn',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='texto2en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='texto2es',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='texto3en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='texto3es',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='texto4en',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='texto4es',
        ),
        migrations.AddField(
            model_name='aboutus',
            name='subtitulo',
            field=models.CharField(default=1, max_length=100, verbose_name='subtitulo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutus',
            name='texto',
            field=models.TextField(default=1, verbose_name='texto'),
            preserve_default=False,
        ),
    ]
