# Generated by Django 3.2.12 on 2023-01-27 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20230116_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tamanno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('capacidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Calidad_Permitida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tamanno')),
            ],
        ),
    ]
